/*
	Kwicks for jQuery (version 1.5.1)
	Copyright (c) 2008 Jeremy Martin
	http://www.jeremymartin.name/projects.php?project=kwicks
	
	Licensed under the MIT license:
   http://www.opensource.org/licenses/mit-license.php

	Any and all use of this script must be accompanied by this copyright/license notice in its present form.
*/
(function(a){a.fn.kwicks=function(b){var c={isVertical:false,sticky:false,defaultKwick:0,event:"mouseover",spacing:0,duration:500};var d=a.extend(c,b);var e=d.isVertical?"height":"width";var f=d.isVertical?"top":"left";return this.each(function(){container=a(this);var b=container.children("li");var c=d.width/b.length;if(!d.max){d.max=c*b.size()-d.min*(b.size()-1)}else{d.min=(c*b.size()-d.max)/(b.size()-1)}if(d.isVertical){container.css({width:d.width,height:c*b.size()+d.spacing*(b.size()-1)+"px"})}else{container.css({width:d.width,height:b.eq(0).css("height")})}var g=[];for(i=0;i<b.size();i++){g[i]=[];for(j=1;j<b.size()-1;j++){if(i==j){g[i][j]=d.isVertical?j*d.min+j*d.spacing:j*d.min+j*d.spacing}else{g[i][j]=(j<=i?j*d.min:(j-1)*d.min+d.max)+j*d.spacing}}}b.each(function(h){var i=a(this);if(h===0){i.css({left:"0px",width:c})}else if(h==b.size()-1){i.css({right:"0px",width:c})}else{if(d.sticky){i.css({LoT:g[d.defaultKwick][h],width:c})}else{i.css({left:h*c+h*d.spacing,width:c})}}if(d.sticky){if(d.defaultKwick==h){i.css(e,d.max+"px");i.addClass("active")}else{i.css(e,d.min+"px")}}i.css({margin:0,position:"absolute"});i.hover(function(){i.find(".kw_title").stop().fadeTo(500,0);i.find(".kw_desc").stop().animate({opacity:"1",bottom:"0px"},500,"easeOutExpo")},function(){i.find(".kw_title").stop().fadeTo(500,1);i.find(".kw_desc").stop().animate({opacity:"0",bottom:"-500px"},500,"easeOutExpo")});i.bind(d.event,function(){var a=[];var c=[];b.stop().removeClass("active");for(j=0;j<b.size();j++){a[j]=b.eq(j).css(e).replace(/px/,"");c[j]=b.eq(j).css(f).replace(/px/,"")}var k={};k[e]=d.max;var l=d.max-a[h];var m=a[h]/l;i.addClass("active").animate(k,{step:function(i){var j=l!=0?i/l-m:1;b.each(function(i){if(i!=h){b.eq(i).css(e,a[i]-(a[i]-d.min)*j+"px")}if(i>0&&i<b.size()-1){b.eq(i).css(f,c[i]-(c[i]-g[h][i])*j+"px")}})},duration:d.duration,easing:d.easing})})});if(!d.sticky){container.bind("mouseleave",function(){var a=[];var g=[];b.removeClass("active").stop();for(i=0;i<b.size();i++){a[i]=b.eq(i).css(e).replace(/px/,"");g[i]=b.eq(i).css(f).replace(/px/,"")}var h={};h[e]=c;var j=c-a[0];b.eq(0).animate(h,{step:function(h){var k=j!=0?(h-a[0])/j:1;for(i=1;i<b.size();i++){b.eq(i).css(e,a[i]-(a[i]-c)*k+"px");if(i<b.size()-1){b.eq(i).css(f,g[i]-(g[i]-(i*c+i*d.spacing))*k+"px")}}},duration:d.duration,easing:d.easing})})}})}})(jQuery);